# Generated by Django 3.2.4 on 2021-06-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_item',
            name='description',
            field=models.CharField(blank=True, default='No description added', max_length=150),
        ),
        migrations.AlterField(
            model_name='note_item',
            name='summary',
            field=models.TextField(blank=True, default='No summary added'),
        ),
    ]
