# Generated by Django 3.2.4 on 2021-06-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_item', '0002_auto_20210615_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_item',
            name='modified',
            field=models.DateTimeField(editable=False),
        ),
    ]
