# Generated by Django 3.2.4 on 2021-06-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_item', '0003_alter_note_item_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_item',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='note_item',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
